// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClff3xZCRUtr5d5e0NWipZcTCV6g4KdFk',
    appId: '1:855274406737:web:5dcd6ea1fc0fbe16fec970',
    messagingSenderId: '855274406737',
    projectId: 'language-exchange-app-cf264',
    authDomain: 'language-exchange-app-cf264.firebaseapp.com',
    storageBucket: 'language-exchange-app-cf264.appspot.com',
    measurementId: 'G-QD5TRZ4F5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl2FGH04tYy36AJ25T0x_J4eSZc3RvNTc',
    appId: '1:855274406737:android:c15d347812d5e4dcfec970',
    messagingSenderId: '855274406737',
    projectId: 'language-exchange-app-cf264',
    storageBucket: 'language-exchange-app-cf264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4ImfUz0NMGTsg3GVerhi-Lt9gTX3P7w',
    appId: '1:855274406737:ios:31a43ed2c93bdf7efec970',
    messagingSenderId: '855274406737',
    projectId: 'language-exchange-app-cf264',
    storageBucket: 'language-exchange-app-cf264.appspot.com',
    iosBundleId: 'com.example.degree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK4ImfUz0NMGTsg3GVerhi-Lt9gTX3P7w',
    appId: '1:855274406737:ios:b7a077b2c07d445ffec970',
    messagingSenderId: '855274406737',
    projectId: 'language-exchange-app-cf264',
    storageBucket: 'language-exchange-app-cf264.appspot.com',
    iosBundleId: 'com.example.degree.RunnerTests',
  );
}
